# .github/workflows/backend-ci-cd.yml

name: Backend CI/CD

on:
  push:
    branches:
      - main # Jalankan hanya saat ada push ke branch main
    paths:
      - 'backend/**' # Hanya jalankan jika ada perubahan di dalam direktori backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend # Set direktori kerja default untuk semua command

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Gunakan versi Node.js yang sesuai
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: yourdockerhubusername/sistem-air-backend:latest # Ganti dengan nama image Anda

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Tarik image Docker terbaru dari registry
            docker pull yourdockerhubusername/sistem-air-backend:latest
            # Hentikan dan hapus kontainer yang sedang berjalan (jika ada)
            docker stop sistem-air-backend-container || true
            docker rm sistem-air-backend-container || true
            # Jalankan kontainer baru dari image yang baru
            docker run -d --restart always \
              -p 3000:3000 \
              --name sistem-air-backend-container \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              yourdockerhubusername/sistem-air-backend:latest